const menuData = [
  {
    title: "Закуски",
    items: [
      {
        name: "Брускетта",
        image: "bruschetta.jpg",
        alt: "Bruschetta",
        description: "Підсмажений хліб зі смачною начинкою.",
        ingredients: "Цільнозерновий багет, авокадо, лосось, томати, спеції.",
        price: 7.99,
      },
      {
        name: "Креветки в часниковому соусі",
        image: "garlic_shrimp.jpg",
        alt: "Garlic Shrimp",
        description: "Соковиті креветки, обсмажені в часниковому соусі.",
        ingredients: "Креветки, часник, вершкове масло, петрушка, лимонний сік.",
        price: 9.99,
      },
      {
        name: "Фаршировані гриби",
        image: "stuffed_mushrooms.jpg",
        alt: "Stuffed Mushrooms",
        description: "Гриби фаршировані сиром та зеленню.",
        ingredients: "Гриби, вершковий сир, пармезан, часник, зелень.",
        price: 8.99,
      },
      {
        name: "Сирна тарілка",
        image: "cheese_platter.jpg",
        alt: "Cheese Platter",
        description: "Асорті сирів з фруктами і горіхами.",
        ingredients: "Брі, чеддер, гауда, волоські горіхи, виноград, мед.",
        price: 12.99,
      },
    ],
  },
  {
    title: "Салати",
    items: [
      {
        name: 'Салат "Цезар"',
        image: "caesar_salad.jpg",
        alt: "Caesar Salad",
        description:
          'Листовий салат ромен з пармезаном, крутонами та соусом «Цезар».',
        ingredients: "Салат ромен, пармезан, крутони, соус «Цезар», анчоуси.",
        price: 12.99,
      },
      {
        name: "Грецький салат",
        image: "greek_salad.jpg",
        alt: "Greek Salad",
        description: "Свіжі помідори, огірки, оливки та сир фета.",
        ingredients: "Помідори, огірки, оливки, фета, червона цибуля, оливкова олія, спеції.",
        price: 11.49,
      },
      {
        name: "Салат Капрезе",
        image: "caprese.jpg",
        alt: "Caprese Salad",
        description: "Помідори, моцарела та базилік зі справжнім італійським бальзамічним соусом.",
        ingredients: "Помідори, моцарела, базилік, більзамічний соус, оливкова олія.",
        price: 10.99,
      },
      {
        name: "Салат з кіноа",
        image: "quinoa_salad.jpg",
        alt: "Quinoa Salad",
        description: "Кіноа з авокадо, болгарським перцем та цитрусовою заправкою.",
        ingredients: "Кіноа, авокадо, болгарський перець, заправка з лайма, кінза",
        price: 13.49,
      },
    ],
  },
  {
    title: "Перші страви",
    items: [
      {
        name: "Томатний крем-суп",
        image: "tomato_soup.jpg",
        alt: "Tomato Soup",
        description: "Наваристий вершковий томатний суп із зеленню..",
        ingredients: "Помідори, базилік, вершки, часник, цибуля.",
        price: 7.99,
      },
      {
        name: "Курячий більйон",
        image: "chicken_soup.jpg",
        alt: "Chicken Soup",
        description: "Класичний курячий бульйон з овочами.",
        ingredients: "Курка, морква, селера, цибуля, часник, бульйон.",
        price: 8.49,
      },
      {
        name: "Грибний крем-суп",
        image: "mushroom_soup.jpg",
        alt: "Mushroom Soup",
        description: "Шовковистий грибний суп з вершковою ноткою.",
        ingredients: "Гриби, вершки, вершкове масло, цибуля, чебрець.",
        price: 9.49,
      },
      {
        name: "Суп з морепродуктів",
        image: "seafood_soup.jpg",
        alt: "Seafood Soup",
        description: "Смачний суп з креветками, мідіями та рибою.",
        ingredients: "Креветки, мідії, риба, помідори, часник, зелень.",
        price: 12.99,
      },
    ],
  },
  {
    title: "Основні страви",
    items: [
      {
        name: "Яловичий стейк",
        image: "beef_steak.jpg",
        alt: "Beef Steak",
        description: "Стейк з яловичини на грилі зі смаженою картоплею.",
        ingredients: "Яловичина, сіль, перець, часник, вершкове масло, смажена картопля.",
        price: 22.99,
      },
      {
        name: "Лосось на грилі",
        image: "salmon.jpg",
        alt: "Grilled Salmon",
        description: "Свіжий лосось смажений на грилі з травами",
        ingredients: "Лосось, лимон, кріп, оливкова олія.",
        price: 18.99,
      },
      {
        name: "Паста \"Карбонара\"",
        image: "carbonara.jpg",
        alt: "Pasta Carbonara",
        description: "Класична італійська паста з гуанчале і з соусом з яєчного жовтка, сиру пекоріно романо.",
        ingredients: "Спагеті, гуанчале, яйця, сир пекоріно, чорний перець.",
        price: 15.49,
      },
      {
        name: "Піца \"Маргарита\"",
        image: "pizza.jpg",
        alt: "Margherita Pizza",
        description: "Піца з печі на дровах з томатами й моцірелою.",
        ingredients: "Тісто з цільнозернового борошна, томатний соус, моцірела, пармезан, томати, базилік, спеції.",
        price: 14.99,
      },
    ],
  },
  {
    title: "Десерти",
    items: [
      {
        name: "Шоколадний торт",
        image: "chocolate_cake.jpg",
        alt: "Chocolate Cake",
        description: "Багатий на смак торт з шоколадним бісквітом й ганашем.",
        ingredients: "Чорний шоколад, какао, борошно, яйця, коричневий цукор, лимонна цедра.",
        price: 9.99,
      },
      {
        name: "Чізкейк",
        image: "cheesecake.jpg",
        alt: "Cheesecake",
        description: "Ніжний чізкейк з ягідним соусом.",
        ingredients: "Крем-сир, яйця, пісочне тісто, цукор, якідний соус.",
        price: 10.49,
      },
      {
        name: "Тірамісу",
        image: "tiramisu.jpg",
        alt: "Tiramisu",
        description: "Класичний італійський десерт.",
        ingredients: "Маскарпоне, кава, савоярді, цукор, ром, какао.",
        price: 11.99,
      },
      {
        name: "Морозиво",
        image: "ice_cream.jpg",
        alt: "Ice Cream",
        description: "Власне морозиво з відбірних інгредієнтів в асортименті",
        ingredients: "",
        price: 7.99,
      },
    ],
  },
  {
    title: "Напої",
    items: [
      {
        name: "Кава в асортименті",
        image: "coffee.jpg",
        alt: "Coffee",
        description: "Запашна кава зі свіжомелених зерен.",
        ingredients: "",
        price: 4.99,
      },
      {
        name: "Чай",
        image: "tea.jpg",
        alt: "Tea",
        description: "Широкий вибір від класичних китайськів чаїв до трав'яних.",
        ingredients: "",
        price: 3.99,
      },
      {
        name: "Апельсиновий фреш",
        image: "orange_juice.jpg",
        alt: "Orange Juice",
        description: "Фреш з відбірних соковитих апельсинів.",
        ingredients: "",
        price: 5.49,
      },
      {
        name: "Червоне вино",
        image: "red_wine.jpg",
        alt: "Red Wine",
        description: "Бокал високоякісного червоного вина.",
        ingredients: "",
        price: 8.99,
      },
    ],
  },
];

export default menuData;